import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./navbar";
import Home from "./main";
import Modal from "./modal";
import { outfit } from "./fonts/fonts";
import { ConfigProvider } from "@/context/configcontext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Decentralized Exchange",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className}`}>
        <ConfigProvider>
          <Navbar />
          <Modal />
          <Home />
        </ConfigProvider>
      </body>
    </html>
  );
}
